languageCode:           "en"
title:                  "CoreUI"
baseURL:                "https://coreui.io/docs/"
enableInlineShortcodes: true

markup:
  goldmark:
    renderer:
      unsafe:           true
  highlight:
    noClasses:          false
  tableOfContents:
    startLevel:         2
    endLevel:           6

buildDrafts:            true
buildFuture:            true

enableRobotsTXT:        true
metaDataFormat:         "yaml"
disableKinds:           ["404", "taxonomy", "taxonomyTerm", "RSS"]

publishDir:             "_gh_pages"

module:
  mounts:
    - source:           dist
      target:           static/4.0/dist
    - source:           docs/assets
      target:           assets
    - source:           docs/content
      target:           content
    - source:           docs/data
      target:           data
    - source:           docs/layouts
      target:           layouts
    - source:           docs/static
      target:           static
    - source:           docs/static/4.0/assets/img/favicons/apple-touch-icon.png
      target:           static/apple-touch-icon.png
    - source:           docs/static/4.0/assets/img/favicons/favicon.ico
      target:           static/favicon.ico

params:
  description:          "The most popular HTML, CSS, and JS library in the world."
  authors:              "Mark Otto, Jacob Thornton, and Bootstrap contributors"
  social_image_path:    /4.0/assets/brand/bootstrap-social.png
  social_logo_path:     /4.0/assets/brand/bootstrap-social-logo.png

  current_version:      "4.0.0-alpha.0"
  current_ruby_version: "4.0.0-alpha.0"
  docs_version:         "4.0"
  rfs_version:          "9.0.3"
  github_org:           "https://github.com/coreui"
  repo:                 "https://github.com/coreui/coreui"
  twitter:              "core_ui"
  community:            "https://community.coreui.io/"
  opencollective:       "https://opencollective.com/bootstrap"
  blog:                 "https://coreui.io/blog/"
  icons:                "https://icons.coreui.io/"

  download:
    source:             "https://github.com/coreui/coreui/archive/v4.0.0-alpha.0.zip"
    dist:               "https://github.com/coreui/coreui/releases/download/v4.0.0-alpha.0/coreui-4.0.0-alpha.0-dist.zip"
    # dist_examples:      "https://github.com/twbs/bootstrap/releases/download/v5.0.0-beta1/bootstrap-5.0.0-beta1-examples.zip"

  cdn:
    # See https://www.srihash.org for info on how to generate the hashes
    # css:              "https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css"
    # css_hash:         "sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1"
    # css_rtl:          "https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.rtl.min.css"
    # css_rtl_hash:     "sha384-mUkCBeyHPdg0tqB6JDd+65Gpw5h/l8DKcCTV2D2UpaMMFd7Jo8A+mDAosaWgFBPl"
    # js:               "https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js"
    # js_hash:          "sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj"
    # js_bundle:        "https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
    # js_bundle_hash:   "sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
    # popper:           "https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"
    # popper_hash:      "sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU"
    css:             "https://cdn.jsdelivr.net/npm/@coreui/coreui@3.3.0/dist/css/coreui.min.css"
    css_hash:        "sha384-/F25cQgfEJPI8yo3LHTPmd1+KyQUPArNFgX31S1wPPF6qfKKofYRZ6moN+Ise6N7"
    css_rtl:          "https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.rtl.min.css"
    css_rtl_hash:     "sha384-Pgl3yA+g7Yp9+m06X5iqRl4y3KVBU8g4/h4w6wZh8YpDOoh1Urms1dzWrnCpYVCy"
    js:              "https://cdn.jsdelivr.net/npm/@coreui/coreui@3.3.0/dist/js/coreui.min.js"
    js_hash:         "sha384-mWOVrAUU044thv3wDk80IN5yGOxg/YjCq+h2uT3mcOg2UXB8VuI3SIY7NjQZdakh"
    js_bundle:       "https://cdn.jsdelivr.net/npm/@coreui/coreui@3.3.0/dist/js/coreui.bundle.min.js"
    js_bundle_hash:  "sha384-bFFwHg1b2BzdcAD2h8KG2m89hpFx7vHhbmlfIid6hF8Ij26jeJZttIUKyv58cSqA"
    icons:           "https://cdn.jsdelivr.net/npm/@coreui/icons@2.0.0-beta.5/css/all.min.css"
    icons_hash:      "sha256-9lgzdlbqBLSfDfASJahkJJk4MW/OaaP+acV9jOomGuo="
    popper:          "https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"
    popper_hash:     "sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU"
